language: node_js
node_js:
  - '5'
deploy:
  -
    provider: heroku
    api_key:
      secure: VOi8oJAl17lt2mD8USnSioTuzZgsTWlhp4pytbGShTzezCLuiwnXh9sio3z+TGwYzrkAx/BaBrAx2uHKPwm3cq7j8lg8Obj/LQAtnPMl4wC7y48ohbizqzt9AZESB7tnovVuta1oBgQAvsPTVptwOVSbJSk4Wd/o9V5wvCQD56CvqyhyabSq2629gb6USgGPtJB60Ij6IIoMvm9BXTDv0D2qhXgYPiOZSa4EJDjBkm1nijtWTqT5vnQAAZ90fSide+ALsYpJSNLddbXbF3y2AR7upw6REDG7X2SV29GRnFZgkKDNPavlp1g1S+RMUzxWfCstBqLm57jalGNjxvWlmYIie85kI/fRBNUEdFofOqnY7C5KBCjfynraLBVQicESRd0sDk5AWQkmM2hunB6tlMaLdGqMy14u30d+NEsS5zaFSJNrUbGV7zf/44oYodmvGjS/b676C8zLCDGH4NxoEBizH+lIkIUiaYxge4IyQkRjfCTta0eCHkkjRCzZyWJXI3GAxlZsH7TH1q/MotrwTsZmY4F6OLkp24g34KCEAz4LJ/7bmWYJNgf9M/XCiOurj3JFX2hf+9nt6SzoMIHwfAhso3jYBL6AoYjz3NAr3Wv4OQxOQ4UgiZGL0UPevsmEXzXZeB1eiShXRTaBAKoqxSMdzTfsB5nhyZ0nP3GENNs=
      app: 
      dev: immense-ridge-70180
  - 
    provider: openshift
    user: me@nomkhonwaan.com
    password:
      secure: p4v0ZXCYbhce4m86ICJb8XTw8gYrp3DoedetZDDY3EHSscooLrJyOxjPEBB54E6v9KVbRtjO5wFUITpawCDdY3JVdF7mJeFcAdAQzGLdkhHbexEfXyWItXoMCnIajULyxRVWF6zGNPOz4YPVCUCjBTlSvNtcJHdaQ7OMd1gPJ+IvAd+2leKFS8QzUZlv88c/kgZ7we55nDjSt4O6cyQ29+VOdePszPqVsX7mySEMyfPjnkblTuF0/aQhmE3bFqDjbQm1l8wO2ehyIUZ20kTyabG+pjq3FLwsPX9kjTFS5HVSdKXXta+ViLbiVi9WzYQ9rDgdpdQKjAYsbpKzliNp3uLibempe0j9hiDljK1nxU/SmAHEUgdtFvLm+n2kRke6aujt20ZXlOXCvSSCKIMi2PKwGK3n/5I/VCYGDVkjtqei5A4G2RmhPC2h3AE4g/2zM74XRzibOZIUO+RZruvYfwMD77S0siHxAjWgQAHeTWUSMCRoBepgtllSampkFdOYcQLyIt3mnn3mBvXLEhN2qvaPcBtekKxAwBZ68M3DyJCSgHlhIxKqqekdsg6kN3xB49xbmuj6+IfTF+fAL6OnLWQqgcOEsIIXMDyrbb/d8KiWO001XjOVg+htMUh0bAeaTsCEnn1sxINdqNf0yz3f7yXyqg8PfOnyX1IS9QuncBE=
    app: beta
    domain: nomkhonwaan
    on:
      branch: dev