language: node_js
node_js:
- '5'
deploy:
  provider: openshift
  user: me@nomkhonwaan.com
  password:
    secure: UV7LasaArA84JoGavXrHQbJXLnzBNYaSLgU4OE0cOusTVKdepxHDsVXb3exUKKOKIReNYS74CKP/dbXrfNjEZ6ZJbOowgLuo2IONi7/u/XBj74o0xooDOU6TXPIHB+MZNn6cwvXMgsrJMqLb/zPRhB7pWg2uRknYobkxqTLF0fScAqwNf43Kl1tLN3WagUwAxOgeBDdNhQQdcpoxBCfWVkkTnWp3wWq5xfKlzKBAaM+BW+SzFxbAF6oGzrwMzbPhWlRC0T3Y0A9yzjSjeY4kcZHWbML0uDMz7Qa5oFMdAuABYbP4Dv420p+dNPIvbKT7xXCetp3Zv1c/NiLh+9Y+how5BRBwQ+OPTVgNTAUi9cnpuzuu/X8yQwZW6fIBQQd+xpxJGymmQTY0SE1sZ5y3WVxzQkAvxxvcuIazLI+m6X1kiq8DhQVvfEglWypsMTgLhTWD5NFdISzJNix5OSzrNHEM4MnXSd6Vl/kj1D4Z6HaSYvHXAC8sddOpPvuWg+Er3BMJhEpt1Zitp3SCUO3/bbkTQGZU8xCxRoF1KyTNlTOjndixF0VM99XsjUz4IQuRkn9eMgnMXW/H6yWiLsEaHM++URyT4lqcWo3F0IR5iQ4R70/IMs7Ffvxh/tpmFriiFDsy9cbOBZglwHNSnhExerYJKVqCG+ryWvStc5xzdkM=
  app: nodejs
  domain: nomkhonwaan
  on:
    repo: nomkhonwaan/nomkhonwaan.com
    branch: dev
