sudo: required
language: node_js
node_js:
- '5'
branches:
  only:
  - dev
services:
- docker
after_success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker build -t nomkhonwaan/blog:latest .
- docker push nomkhonwaan/blog:latest
env:
  global:
  - secure: XtUuXKDSJCniG23qnJ0CQH6aEAxApEqlJm3tFf4fjtbzxVcaQXm6uBf7w20JQzRbd88iigl5GEmTCodquKVvDzkTUUTcuDbyu2PMKGLXa6rBoRyzfUA3I89R7XgmZ7ryzNhGNJRC9qV8Cz6NVI5Z8mf3AkBZxq3/pO8MUMnPmtvH9MoxzRGAuhlSEERXkqOPVVLg20kfKYV2ItQ3mp5HlrVmJt2XYAk8IMkIirVVmDxCf7Ro7uVkVuvq42m7998gu/J4O9ZzdrOJUfelMJXZxPCcIqk42/LmsZSrfikvEyJaNh58N+TmWsf29RpqCmuHTWnciflCCy0nVJ6fm+hyw0bt8+KJd56Jyo+Bf6aum/oE2fyX/L6Z0MsDfw4aup+XGev6lKWAK87B4S3DXpDUfm9vxchrffoWrKkC4bJnx77pjoqXEYbND3O7iRt87gp1oeEhsHGxbU/Q4HwEbdGdvIVZ1grlYu6kbJoBWnkKqCC2LQPQ4lNG27krAfTrTYOvywlXHi77Rbjp7TPqbQM5TZJLGHfwCoDJWX+mcL4A99y7S+joaZgYOcW+lJ3DRCKpz7+UJL18Z19FdNj83XKb0Z41njsIaGHCQ3EEG5irB4pts9icMKX9FadtrkTD86Wp8uLpCPVRgdeGpaCMeocdy0qv3kt8RFrltNLbvq2Ojvw=
  - secure: Bb8ybE8VCpYW0OBigkkKBQogL5Ugye2iQXJH4xaUW9n4Xvz+5wEBNSfq0FpOCB1GD82y/qB+WhETxV6Rxb5KhDnnOrDWJa/C4ftDk8TcQI4T05saZCLnzDsYyowR9En3R9NyM2sU2YwCkLXSTQ6assDS5MdaswISLsX028+tSVx3lT8P/y9FHQ8NvYtRh47r0MZeGAxw7Yjf/ygJGufahhhicmTt4nOx0cShUTbwQABegpuJoVsi6M9wYYc78bM44uTugSvOB/povMitoFFE5/D5xrqZsK/UUnFGRw2NGje++fFENRFPJqQMt7OIueX9GRksmeKRX7Bs6JJ5E1oXZs5fF56ZLNEIy5OrViwTuaVeAooNRryJrRSSem1Yy+ZnFIcmFBxDZMqN+K2v3+Y+TYBBNOOpmhSqWP5QrBawc06NcpIpWOf1sUipDOTZCOF1zZ/v6Pbq2zs6YJjZuRnDdwNRfmIgvxfXNMpPumNEl+0qoPjdkfh6bvOeEBCb1CHPCcKhSNeY00Yav/u0A9cqmPF0a43vOirb4E3olUCdbotSt4vwJ1eh3eDw3nEQK+xcM+Prk+iSmrAwoo+dZoOImiDfCJzLwIDPYG9EnTp5n0FT95hQQICNe35FkZ0o8646Jq3+uuuRdGZfVRVhLFR8s6hkQNSQZZKifk4Q2qcr4NQ=
