language: node_js
node_js:
- '5'
deploy:
  -
    provider: heroku
    api_key:
      secure: $HEROKU_SECURE
    app: immense-ridge-70180
    on:
      repo: nomkhonwaan/nomkhonwaan.com
      branch: dev