language: node_js
node_js:
- '5'
deploy:
  provider: openshift
  user: me@nomkhonwaan.com
  password:
    secure: MDu0RzCvZUWOxfU/kL4triba8obu0LdjWICGeOUuOc65kicdlvvu7oROYp7zW/bqfgxu7aIkMM3VjVMRl78KzfpvxQNDv8rhQ0oJerKw7mrgayvory3w8SNEwIB05Wa7AJgSeR39oL/NRXQ5+mC4g5lbLq5lAV0NTwLL4rRtIWRAbPOd/PP5wVRkdZaEfC61Waqcd14yiUZPgfcIak2g/dcfrXeY6puxzdIXBC1vQH+AyiXE2zgPKQmo+nTJdSc7AVuvEkcxL2McxBD9/XDN67iIP4G68L89NW9xYgPXuwXkJeujBoXxy9Y2Av4jO5BMHfTHmoSHwnRpUDW35zuw52mov0KT5NcohhT1WBGKZq982wmjP/oVniAWuoSuWsahQr7VYp7g3C5jsPvefkZxQhkvXw2ccgGC6RqXQQu5j7NytERs5rScn/3H/blM3CL5Ck2gvUUT9Iej8268qTfxCK7nsqOxmVl1gpnkhyyPt/QeqbI6CaEaCX+czMYZBPYSJbTjrgrWQlt/Y7/Xf3tvU32dWqeoYlaamHvUpRbfscV1ZMPwcdcpyAGrRqLZUoWCzpbhQ4lxf5xUDC3f++ho4YDO/0uYfxZ4DgIgOMr1U67n+8XAtNLwn2Em41M1GZbmujeo4f80I5jAz4eSaRZc1rZgJgoatVWOMPae2D7mYcg=
  app: beta
  domain: nomkhonwaan
  on:
    repo: nomkhonwaan/nomkhonwaan.com
    branch: dev
