version: '2'
services:
  mongo_data:
    image: alpine:latest
    volumes:
      - ~/mongodb:/data/db
    command: /bin/true
  mongo:
    image: mongo:latest
    volumes_from:
      - mongo_data
  mongo_express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    links:
      - mongo
  elasticsearch:
    image: elasticsearch:latest
  kibana:
    image: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch
  nomkhonwaan_com:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3003:8080
    links:
      - mongo
      - elasticsearch