version: '2'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb:/data/db
  mongo_express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    links:
      - mongo 
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_PORT: '27017'
  redis:
    image: redis:latest
    ports:
      - 6379:6379
