version: '2'
services:
  mongo_data:
    image: alpine:latest
    volumes:
      - ~/mongodb:/data/db
    command: /bin/true
  mongo:
    image: mongo:latest
    volumes_from:
      - mongo_data
    ports:
      - 27017:27017
  mongo_express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_PORT: '27017'
  redis:
    image: redis:latest
  nomkhonwaan_com:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3003:8080
    links:
      - mongo
      - redis