version: '2'
services:
  mongo_data:
    image: alpine:latest
    volumes:
      - ~/mongodb:/data/db
    command: /bin/true
  mongo:
    image: mongo:latest
    volumes_from:
      - mongo_data
  mongo_express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_PORT: '27017'
      MONGODB_URI: mongodb://mongo:27017/nomkhonwaan_com
  redis:
    image: redis:latest
  nomkhonwaan_com:
    image: nomkhonwaan/nomkhonwaan.com:latest 
    ports:
      - 3003:8080
    links:
      - mongo
      - redis
    environment:
      MONGODB_URI: mongodb://mongo:27017/nomkhonwaan_com
      REDIS_URL: redis://redis:6379