version: '2'
services:
  mongo_data:
    image: alpine:latest
    volumes:
      - ~/mongodb:/data/db
    command: /bin/true
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes_from:
      - mongo_data
  mongo_express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_PORT: '27017'
  redis:
    image: redis:latest
    ports:
      - 6379:6379
