version: '2'
services:
  mongo-data:
    image: alpine:latest
    volumes:
      - ~/mongodb:/data/db
    command: /bin/true
  mongo:
    image: mongo:latest
    volumes_from:
      - mongo-data
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    links:
      - mongo
    restart: always
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3003:8080
    links:
      - mongo
    restart: always