import constants from 'flux-constants'

export default constants([

  'NAV_TOGGLE_MENU_BUTTON',

  'POSTS_PAGE_CHANGE',
  'POSTS_PAGE_REQUEST',
  'POSTS_PAGE_SUCCESS',
  'POSTS_PAGE_FAILURE',
  'POSTS_TOGGLE_POPUP_POST',

  'POSTS_POST_CHANGE',
  'POSTS_POST_REQUEST',
  'POSTS_POST_SUCCESS',
  'POSTS_POST_FAILURE',

])
